config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :flats, only: [:index, :new, :create, :edit, :show, :update ] do
    resources :reviews, only: [:new, :create]
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
    has_many :reviews, dependent: :destroy
    validates :name, :address, :price_per_night, :number_of_guests, presence: true
    validates :description,  length: { minimum: 10}, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :flat
  validates :review, length: { minimum: 10 }, presence: true
  validates :rating, length: { in: 0..5 }, presence: true, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :find_flat, except: [:index, :new, :create]

  def index
    @flats = Flat.all
  end

  def show
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flats_params)
    @flat.save
    redirect_to flats_path
  end
  
  def edit
  end
  
  def update
    @flat.update(flats_params)
    redirect_to flats_path
  end

  private

  def flats_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end

  def find_flat
    @flat = Flat.find(params[:id])
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :find_flat

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.flat = @flat
    if @review.save
      redirect_to flat_path(@flat)
    else
      render "reviews/new"
    end
  end

private

  def review_params
    params.require(:review).permit(:review, :rating)
  end

  def find_flat
    @flat = Flat.find(params[:flat_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for @flat do |form| %>
  <%= form.input :address %>
  <%= form.input :description %>
  <%= form.input :price_per_night %>
  <%= form.input :number_of_guests %>
  <%= form.input :name %>
  <%= form.button :submit, class:"btn btn-warning" %>
<% end %>

app/views/flats/edit.html.erb
<%= render "form" %>

app/views/flats/index.html.erb
<h3>All Our Flats, all of them</h3>
<br>

<div class="container">

  <div class="row row-cols-3">
    
    <% @flats.each do |flat|  %>

    <div class="col">
    
        <div class="card" style="width: 18rem;">
         <%# <img src="..." class="card-img-top" alt="..."> %>
         <div class="card-body">
           <h5 class="card-title"><a><%= link_to "#{flat.address}", flat_path(flat.id) %></a></h5>
           <p class="card-text"> <%= "#{flat.description}" %> </p>
         </div>
         <ul class="list-group list-group-flush">
         <div class = "d-flex p-2 justify-content-evenly">
           <div class="d-inline-flex p-2 align-items-center">
             <i class="material-icons">people</i>
             <li class="list-group-item"><%= "#{flat.number_of_guests}" %></li>
           </div>


           <div class="d-inline-flex p-2 align-items-center">
             <i  class="material-icons ">euro_symbol</i>
             <li class="list-group-item"><%= "#{flat.price_per_night}" %></li>
           </div>  

           <li class="list-group-item">Rating</li>
         </div>
         </ul>
         <div class="card-body">
           <a href="#" class="card-link"><%= link_to "Find Out more", flat_path(flat.id) %></a> | 
         </div>
       </div>
       <br>
       <% end %>

    </div>
  </div>


</div>




<a>  <%= link_to "New Flat", new_flat_path %>  </a>

app/views/flats/new.html.erb
<%= render "form" %>

app/views/flats/show.html.erb
<h6>This is the Flat Show page</h6>
<br>

<h2> <%= "#{@flat.address}" %>  </h2>
<h4> <%= "Price per night £:#{@flat.price_per_night}" %>  </h4>
<h4> <%= "Maximum number of guests: #{@flat.number_of_guests}" %>  </h4>
<h5> <%= "Details:"  %>  </h5>
<h5> <%=  "#{@flat.description}" %>  </h5>
<h5> <%= "Contact: #{@flat.name}" %>  </h5>
<h5> <%= "REVIEWS:"  %>  </h5>
  <ol>
    <% @flat.reviews.each do |review| %>  
    <li>  
      <h5> <%= " #{review.review}" %>  </h5>
      <h5> <%= " Rating: #{review.rating}" %>  </h5> 
    </li>
    <% end %>
  </ol>
  

<br>
<a> <%= link_to "Back to Flats", flats_path %>  </a> |
<a> <%= link_to "Edit", edit_flat_path(@flat) %>  </a> | 
<a> <%= link_to "Add a Review", new_flat_review_path(@flat) %>  </a> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
     <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">  
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reviews/_review.html.erb
<%= simple_form_for [@flat, @review] do |form| %> 
  <%= form.input :review %>
  <%= form.input :rating %>
  <%= form.button :submit %>
<% end %>

app/views/reviews/new.html.erb
<h2> <%= "#{@flat.address}" %>  </h2>
<h4> <%= "Price per night £:#{@flat.price_per_night}" %>  </h4>
<h4> <%= "Maximum number of guests: #{@flat.number_of_guests}" %>  </h4>
<h5> <%= "Details:"  %>  </h5>
<h5> <%=  "#{@flat.description}" %>  </h5>
<h5> <%= "Contact: #{@flat.name}" %>  </h5>
<br>
<h5> <%= "Add your Review and rating below" %>  </h5>
<br>

<%= render "review" %>

<a> <%= link_to "Cancel", flat_path(@flat) %> </a>